blueprints/qa.py
from flask import Blueprint,render_template,request,g,session,redirect,url_for,flash
from decorators import login_required
from .forms import QuestionForm,AnswerForm
from models import QuestionModel,AnswerModel
from exts import db

bp = Blueprint("qa",__name__,url_prefix="/")

@bp.route("/")
def index():
    questions = QuestionModel.query.order_by(db.text("-create_time")).all()
    return render_template("index.html",questions=questions)

@bp.route("/public/question", methods=["GET","POST"])
@login_required
def public_question():
    if request.method == "GET":
        return render_template("public_question.html")
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            context = form.context.data
            question = QuestionModel(title=title,context=context,author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect("/")
        else:
            flash("标题或内容不满足要求! ")
            return redirect(url_for("qa.public_question"))


@bp.route("/question/<int:question_id>")
def question_detail(question_id):
    question = QuestionModel.query.get(question_id)
    return render_template("detail.html",question=question)

@bp.route("/answer/<int:question_id>",methods=["POST"])
@login_required
def answer(question_id):
    form = AnswerForm(request.form)
    if form.validate():
        context = form.context.data
        answer_model = AnswerModel(context=context,author=g.user,question_id=question_id)
        db.session.add(answer_model)
        db.session.commit()
        return redirect(url_for("qa.question_detail",question_id=question_id))
    else:
        flash("表单验证失败")
        return redirect(url_for("qa.question_detail",question_id=question_id))

blueprints/user.py
import random
import string
from datetime import datetime

from flask import Blueprint,render_template,request,redirect,url_for,jsonify,session,flash
from exts import mail,db
from flask_mail import Message
from models import EmailCaptchaModel,UserModel
from .forms import RegisterForm,LoginForm
from werkzeug.security import generate_password_hash,check_password_hash


bp = Blueprint("user",__name__,url_prefix="/user")

@bp.route("/login",methods=["POST","GET"])
def login():
    if request.method == "GET":
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password,password):
                session['user_id'] = user.id
                return redirect("/")
            else:
                flash("邮箱密码不匹配")
                return redirect(url_for("user.login"))
        else:
            flash("邮箱或密码格式不正确")
            return redirect(url_for("user.login"))

@bp.route("/register",methods=["POST","GET"])
def register():
    if request.method == "GET":
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        # 如果验证通过
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data

            hash_password = generate_password_hash(password)
            user = UserModel(email=email, username=username, password=hash_password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("user.register"))


@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("user.login"))

@bp.route("/captcha",methods=["POST"])
def get_captcha():
    #get,post
    email = request.form.get("email")
    letters = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letters,4))
    if email:
        message = Message(
            subject="邮箱测试",
            recipients=[email],
            body=f"您的注册验证码是:{captcha}"
        )
        mail.send(message)
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.creat_time =datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCaptchaModel(email=email,captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
            print("captcha:",captcha)
        return jsonify({"code":200})
    else:
        return jsonify({"code":400,"message":"请先传递邮箱!"})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static',filename = 'bootstrap/bootstrap@4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'css/init.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
<!--导航条-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
          <a class="navbar-brand" href="#">知了问答</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for("qa.index") }}">首页 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{{ url_for('qa.public_question') }}">发表问答</a>
      </li>
        <li class="nav-item ml-2">
             <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
    </form>
        </li>
    </ul>
      <ul class="navbar-nav ">
      {% if user %}
        <li class="nav-item ">
        <span class="nav-link">{{ user.username }}</span>
        </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.logout') }}">注销</a>
      </li>
      {% else %}
        <li class="nav-item ">
        <a class="nav-link" href="{{ url_for('user.login') }}">登录 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
      </li>
      {% endif %}
    </ul>
  </div>
    </div>
</nav>
<div class="container">
    {% block body %}{% endblock %}
</div>

</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}{{ question.title }}{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{% endblock %}

{% block body %}
  <div class="row" style="margin-top: 20px">
    <div class="col"></div>
    <div class="col-8 "  style="background-color: #fff; padding: 20px">
      <h3 class="page-title">{{ question.title }}</h3>
      <p class="question-info">
        <span>作者:{{ question.author.username }}</span>
        <span>时间:{{ question.create_time }}</span>
      </p>
      <hr>
      <p class="question-content">{{ question.context }}</p>
      <hr>
      <h4 class="comment-group-title">评论({{ question.answers|length }})</h4>
      <form action="{{ url_for('qa.answer',question_id=question.id) }}" method="post">
        <div class="form-group">
          <input type="text" placeholder="请填写评论" name="context" class="form-control">
        </div>

        {% for message in get_flashed_messages() %}
        <div class="form-group">
        <div class="text-danger">{{ message }}</div>
        </div>
      {% endfor %}

        <div class="form-group" style="text-align: right">
          <button class="btn btn-primary">评论</button>
        </div>
      </form>
      <ul class="comment-group">
        {% for answer in question.answers %}
          <li>
          <div class="user-info">
            <img class="avatar" src="{{ url_for('static',filename='/images/yelan.jpg') }}" alt="图片">
            <span class="username">{{ answer.author.username }}</span>
            <span class="create-time">{{ answer.create_time }}</span>
          </div>
          <p class="comment-content">{{ answer.context }}</p>
        </li>
        {% endfor %}

      </ul>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}知了问答-首页{% endblock %}

{% block head %}
 <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block body %}
  <div class="row" style="margin-top: 20px">
  <div class="col"></div>
  <div class="col-8" >
    <ul class="question-ul">
      {% for question in questions %}
        <li>
          <div class="side-question">
            <img class="side-question-avatar" src="{{ url_for('static',filename='images/yelan.jpg') }}" alt="头像">
          </div>
          <div class="question-main">
            <div class="question-title"><a href="{{ url_for('qa.question_detail',question_id=question.id) }}">{{ question.title }}</a></div>
            <div class="question-content">{{ question.context }}</div>
            <div class="question-detail">
              <span class="question-author">{{ question.author.username }}</span>
              <span class="question-time">{{ question.create_time}}</span>
            </div>
          </div>
      </li>
      {% endfor %}
    </ul>
  </div>
  <div class="col"></div>
  </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}知了问答-登录{% endblock %}

{% block head %}{% endblock %}

{% block body %}
  <div class="row mt-4">
  <div class="col"></div>
  <div class="col">
    <form action="{{ url_for('user.login') }}" method="post">

      <div class="form-group">
        <label for="exampleInputEmail1">邮箱</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
      </div>

      <div class="form-group">
        <label for="exampleInputPassword1">密码</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
      </div>

      {% for message in get_flashed_messages() %}
        <div class="form-group">
        <div class="text-danger">{{ message }}</div>
        </div>
      {% endfor %}

      <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block" >立即登录</button>
      </div>

    </form>
  </div>
  <div class="col"></div>
  </div>
{% endblock %}

templates/public_question.html
{% extends "base.html" %}

{% block title %}发表问答{% endblock %}

{% block body %}
<div class="row" style="margin-top: 20px;">
<div class="col"></div>
<div class="col-8">
  <h1 style="text-align: center">发布问答</h1>
  <form action="{{ url_for('qa.public_question') }}" method="post">

    <div class="form-group">
      <input type="text" name="title" class="form-control" placeholder="请输入标题">
    </div>

    <div class="form-group">
      <textarea name="context" class="form-control" rows="10" placeholder="请输入内容"></textarea>
    </div>

    {% for message in get_flashed_messages() %}
      <div class="form-group">
          <div class="text-danger">{{ message }}</div>
      </div>
    {% endfor %}

    <div class="form-group" style="text-align: right">
      <button class="btn btn-primary" type="submit">发布</button>
    </div>
  </form>
</div>
<div class="col"></div>
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}知了问答-注册{% endblock %}

{% block head %}
  <script src="{{ url_for('static',filename='jquery/jquery.3.6.min.js') }}"></script>
  <script src="{{ url_for('static',filename='js/register.js') }}"></script>
{% endblock %}

{% block body %}
   <div class="row mt-4">
  <div class="col"></div>
  <div class="col">
    <form method="POST" action="{{ url_for('user.register') }}" >
      <div class="form-group">
        <label for="exampleInputEmail1">邮箱</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
        <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用途</small>
      </div>

      <div class="form-group">
        <label for="exampleInputEmail1">验证码</label>
        <div class="input-group">
          <input type="text" class="form-control" name="captcha">
          <div class="input-group-append">
          <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
          </div>
        </div>
      </div>

      <div class="form-group">
        <label for="exampleInputEmail1">用户名</label>
        <input type="text" class="form-control"  name="username">
      </div>

      <div class="form-group">
        <label for="exampleInputPassword1">密码</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
      </div>

      <div class="form-group">
        <label for="exampleInputPassword1">确认密码</label>
        <input type="password" class="form-control" name="password_confirm">
      </div>

      <button type="submit" class="btn btn-primary btn-block" >立即注册</button>
    </form>
  </div>
  <div class="col"></div>
  </div>
{% endblock %}